<script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/anchor.min.js"></script>
    <script src="js/is.min.js"></script>
    <script src="js/all.min.js"></script>
    <script src="js/lodash.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="js/list.min.js"></script>
    <script src="js/feather.min.js"></script>
    <script src="js/dayjs.min.js"></script>
    <script src="js/choices.min.js"></script>
    <script src="js/echarts.min.js"></script>
    <script src="js/dhtmlxgantt.js"></script>
    <script src="js/flatpickr.min.js"></script>
    <script src="js/phoenix.js"></script>
    <script src="js/projectmanagement-dashboard.js"></script>
